#!/usr/bin/perl

use strict;
use warnings;

my @files = qw(
    bashrc
    zshenv
    aliasrc
    dirsrc
    inputrc
    perltidyrc
    screenrc
    gitconfig
    tmux.conf
    psqlrc
);

foreach (@files) {
	unless (-f "~/.$_") {
		system "ln -s dotfiles/$_ ~/.$_";
	}
}
