#!/usr/bin/perl

use strict;
use warnings;

foreach (qw(bashrc zshenv aliasrc dirsrc inputrc perltidyrc screenrc gitconfig tmux.conf)) {
	if (-f "~/.$_") {
		warn "~/.$_ already exists\n";
	} else {
		system "ln -s dotfiles/$_ ~/.$_";
	}
}
