#!/usr/bin/perl

use strict;
use warnings;

my @files = qw(
    aliasrc
    bashrc
    dirsrc
    gitconfig
    inputrc
    pentadactyl
    pentadactylrc
    perltidyrc
    prompt
    psqlrc
    screenrc
    tmux.conf
    urlview
    vimperator
    vimperatorrc
    zshenv
);

foreach (@files) {
	unless (-f "~/.$_") {
		system "ln -s dotfiles/$_ ~/.$_";
	}
}
